
enum flight_phases {
    ON_GROUND,
    TAXIING,
    WAITING_CLEARANCE,
    TAKEOFF,
    CLIMBING,
    CRUISING,
    DESCENDING,
    APPROACH,
    LANDING,
    ROLLOUT
};

enum message_types {
    CHECK_IN,
    CHECK_OUT,
    TAXI_REQUEST,
    TAXI_CLEARANCE,
    DESCEND_REQUEST,
    DESCEND_CLEARANCE,
    CLIMBING_REQUEST,
    CLIMBING_CLEARANCE,
    TAKEOFF_REQUEST,
    TAKEOFF_CLEARANCE,
    AFTER_TAKEOFF,
    LANDING_REQUEST,
    LANDING_CLEARANCE,
    AFTER_LANDING,
    GO_AROUND_REQUEST,
    ENTER_HOLDING_REQUEST,
    EXIT_HOLDING_REQUEST,
    EXIT_HOLDING_CLEARANCE
};